sudo: required
addons:
  chrome: stable
branches:
  only:
  - master
  - staging
  - live
before_install:
- wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key |
  sudo apt-key add -
- echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
- sudo apt-get -qq update
- sudo apt-get install cf-cli
script:
- "./infrastructure/ci-user-site-test.sh"
- "./infrastructure/ci-admin-site-test.sh"
deploy:
  provider: script
  script: SPACE=int ./infrastructure/deploy.sh
  on:
    branch: master
after_deploy: "./infrastructure/ci-integration-test.sh"
env:
  global:
  - secure: Wes650c57YRdfzOvzSodNvPOfb3hRbqM+WKmMZGg0MR8eMkF2PLZrZXrRWHvmsxJ0leyAy9OU97veuuLEECg5Jm82K8TGWqsX9yCCkeqsDbMZgH/ErvQJx5sotldbj3u6EZtujUbGuu0zf7gAEmCrOoq6h30k59pGWgQYHDOYCXrQQwOgctQvQ1a3j6atrAFER2WNISlhW1zHwfUvn8qovcdo0yjHLy4vvYZAkrmapfe2eXl+q/FArx503oDIFkGtCgN57lFvxKNBMZltiMmY1QGOAvuuJFTTJbza1/xI0TFJCYWG9dPKLnT68yGySwcuZ6yVpUAI18RJE3EUn2wAkROUDl3cg9zL6j9W+TwXN5sfoNjKD0OoTBuMEcllNM+VQIZZUHCf6TqdLXkF76vZW/apQwarmeDmHsUzAQeoRpy+Uh2PJbUSn1Tp8Gkk+WYl30f84akqWYsnMuxZ1IokG8BeJ0X9tC+g2LnDrlTyAuJ8twjE0559BbqQb37nGY24ha2C+zh9mz6QvVBAArJ7zTTSy914oJBh13Uvi6ybl2HC0fF2sw1PfXmINyXYjaLXACtqi4ptZJi8b3For7RtdoEvEhKbLMj8g3Y2falPG0fZscpPHWPvMVZM7azeokfTuNFYAmu99g/SvGhYN/iZeuKqi0w3ESuh0mskz7qMz8=
  - secure: TNxnkUvgHeJJws/x/43xdV3tul2AkshRrdJ3C3OD9M+TGwhH89UuHIhb7IpRb6cnji515EaKjSQNObnKqdmQHco/2ilZeNHNoqL6CAvhALoM6KezjuWKoDND3QmoOcWuLbasJ0MrUHXdGRd4/r4Q+esDH8A9bJ/+mlr2TWRjYqe0YnmSGvrA9xYPYDoG3esAinasy3icLk6CeKNX4aQbZH6Je4Ur2T/t0LropIpb5Z5L6SHfzKD4jOeun+LIiXnjFQlVWny/paoK0ltfRwQv7niaLq7UMXR1Pd36Wdlgy4pXB9o3Ak+3WFjvfwJUJGK4OAbd+spxDzYCOfiP+4GrRMK22YXROYOKAhN4VjTdx7YYXWrYcMfEcWIUubx4VEi49K/ouBsGhONuuNvBJeQTky25lWSlSzQSvrUbA0anfVAXh7heOamlHdoKcFTGAoDjLBQKLvh8ERiqpJmEritctyRiWrrLGvSAGz/MKUvUxgAZFuo3JhwfT2U5CKuLbImLRxRtlFRyjiBP1/JDhQ6fgOPtJq6g/cps7p0g7uOVbu/1yEAgCSWUFLkEuo9unoQoRXlkvcJjBrmX2SwzhWOK2zymnBv8Xqb5ClJpKg8J+Ak6RI3UF704ir84ItpKGuq1JpyprJzQl94nJvIWrnp9lghPlK0RDC+HmcFNr0LKdq4=
